// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `ListDeals`. */
export interface IListDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
    is_active: IDealsColumns["is_active"];
}

/** Result of query `GetDeal`. */
export interface IGetDealResult {
    id: IDealsColumns["id"];
    amount: IDealsColumns["amount"];
    attachment: IDealsColumns["attachment"];
    closed_at: IDealsColumns["closed_at"];
}

/** Result of query `GetUserDeals`. */
export interface IGetUserDealsResult {
    id: number | null;
    email: IUsersColumns["email"] | null;
    amount: IDealsColumns["amount"] | null;
}

/** Result of query `UserEmails`. */
export interface IUserEmailsResult {
    email: IUsersColumns["email"];
    amount: IDealsColumns["amount"] | null;
}

/** Result of query `DealStats`. */
export interface IDealStatsResult {
    total: number | null;
    loud: unknown | null;
}

/** Result of query `SearchDeals`. */
export interface ISearchDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
}

export interface Queries {
    ListDeals: IListDealsResult;
    GetDeal: IGetDealResult;
    GetUserDeals: IGetUserDealsResult;
    UserEmails: IUserEmailsResult;
    DealStats: IDealStatsResult;
    SearchDeals: ISearchDealsResult;
}

/** Columns of `deal_details`. */
export interface IDealDetailsColumns {
    deal_id: number | null;
    status: string | null;
    amount: number | null;
    email: string | null;
    display_name: string | null;
}

/** Schema of `deal_details`. */
export interface IDealDetailsTable {
    columns: IDealDetailsColumns;
    relationType: (typeof schema)["deal_details"]["_relationType"];
    indexes: keyof (typeof schema)["deal_details"]["_indexes"];
    constraints: keyof (typeof schema)["deal_details"]["_constraints"];
}

/** Columns of `deals`. */
export interface IDealsColumns {
    id: number;
    user_id: number;
    amount: number;
    status: string;
    is_active: number;
    closed_at: string | null;
    attachment: Uint8Array | null;
}

/** Schema of `deals`. */
export interface IDealsTable {
    columns: IDealsColumns;
    relationType: (typeof schema)["deals"]["_relationType"];
    indexes: keyof (typeof schema)["deals"]["_indexes"];
    constraints: keyof (typeof schema)["deals"]["_constraints"];
}

/** Columns of `users`. */
export interface IUsersColumns {
    id: number;
    email: string;
    display_name: string | null;
    created_at: string;
}

/** Schema of `users`. */
export interface IUsersTable {
    columns: IUsersColumns;
    relationType: (typeof schema)["users"]["_relationType"];
    indexes: keyof (typeof schema)["users"]["_indexes"];
    constraints: keyof (typeof schema)["users"]["_constraints"];
}

export const schema = {
    deal_details: {
        _relationName: "deal_details",
        _relationType: "view",
        _columns: {
            deal_id: { _columnName: "deal_id" },
            status: { _columnName: "status" },
            amount: { _columnName: "amount" },
            email: { _columnName: "email" },
            display_name: { _columnName: "display_name" }
        },
        _indexes: {},
        _constraints: {}
    },
    deals: {
        _relationName: "deals",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id" },
            user_id: { _columnName: "user_id" },
            amount: { _columnName: "amount" },
            status: { _columnName: "status" },
            is_active: { _columnName: "is_active" },
            closed_at: { _columnName: "closed_at" },
            attachment: { _columnName: "attachment" }
        },
        _indexes: {},
        _constraints: {}
    },
    users: {
        _relationName: "users",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id" },
            email: { _columnName: "email" },
            display_name: { _columnName: "display_name" },
            created_at: { _columnName: "created_at" }
        },
        _indexes: {},
        _constraints: {}
    }
} as const;

export interface Tables {
    deal_details: IDealDetailsTable;
    deals: IDealsTable;
    users: IUsersTable;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
