// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `ListDeals`. */
export interface IListDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
    is_active: IDealsColumns["is_active"];
}

/** Result of query `GetDeal`. */
export interface IGetDealResult {
    id: IDealsColumns["id"];
    amount: IDealsColumns["amount"];
    attachment: IDealsColumns["attachment"];
    closed_at: IDealsColumns["closed_at"];
}

/** Result of query `GetUserDeals`. */
export interface IGetUserDealsResult {
    id: number | null;
    email: IUsersColumns["email"] | null;
    amount: IDealsColumns["amount"] | null;
}

/** Result of query `UserEmails`. */
export interface IUserEmailsResult {
    email: IUsersColumns["email"];
    amount: IDealsColumns["amount"] | null;
}

/** Result of query `DealStats`. */
export interface IDealStatsResult {
    total: number | null;
    loud: unknown | null;
}

/** Result of query `SearchDeals`. */
export interface ISearchDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
}

export interface Queries {
    ListDeals: IListDealsResult;
    GetDeal: IGetDealResult;
    GetUserDeals: IGetUserDealsResult;
    UserEmails: IUserEmailsResult;
    DealStats: IDealStatsResult;
    SearchDeals: ISearchDealsResult;
}

/** Columns of `deal_details`. */
export interface IDealDetailsColumns {
    deal_id: number | null;
    status: string | null;
    amount: number | null;
    email: string | null;
    display_name: string | null;
}

/** Schema of `deal_details`. */
export interface IDealDetailsTable {
    columns: IDealDetailsColumns;
    indexes: (typeof schema)["deal_details"]["indexes"][number];
    constraints: (typeof schema)["deal_details"]["constraints"][number];
}

/** Columns of `deals`. */
export interface IDealsColumns {
    id: number;
    user_id: number;
    amount: number;
    status: string;
    is_active: number;
    closed_at: string | null;
    attachment: Uint8Array | null;
}

/** Schema of `deals`. */
export interface IDealsTable {
    columns: IDealsColumns;
    indexes: (typeof schema)["deals"]["indexes"][number];
    constraints: (typeof schema)["deals"]["constraints"][number];
}

/** Columns of `users`. */
export interface IUsersColumns {
    id: number;
    email: string;
    display_name: string | null;
    created_at: string;
}

/** Schema of `users`. */
export interface IUsersTable {
    columns: IUsersColumns;
    indexes: (typeof schema)["users"]["indexes"][number];
    constraints: (typeof schema)["users"]["constraints"][number];
}

export const schema = {
    deal_details: { name: "deal_details", columns: ["deal_id", "status", "amount", "email", "display_name"], indexes: [], constraints: [] },
    deals: { name: "deals", columns: ["id", "user_id", "amount", "status", "is_active", "closed_at", "attachment"], indexes: [], constraints: [] },
    users: { name: "users", columns: ["id", "email", "display_name", "created_at"], indexes: [], constraints: [] }
} as const;

export interface Tables {
    deal_details: IDealDetailsTable;
    deals: IDealsTable;
    users: IUsersTable;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
