// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `ListDeals`. */
export interface IListDealsResult {
    id: number;
    status: string;
    amount: number;
    is_active: number;
}

/** Result of query `GetDeal`. */
export interface IGetDealResult {
    id: number;
    amount: number;
    attachment: Uint8Array | null;
    closed_at: string | null;
}

/** Result of query `GetUserDeals`. */
export interface IGetUserDealsResult {
    id: number | null;
    email: string | null;
    amount: number | null;
}

/** Result of query `UserEmails`. */
export interface IUserEmailsResult {
    email: string;
    amount: number | null;
}

/** Result of query `DealStats`. */
export interface IDealStatsResult {
    total: number | null;
    loud: unknown | null;
}

/** Result of query `SearchDeals`. */
export interface ISearchDealsResult {
    id: number;
    status: string;
    amount: number;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults {
        ListDeals: IListDealsResult;
        GetDeal: IGetDealResult;
        GetUserDeals: IGetUserDealsResult;
        UserEmails: IUserEmailsResult;
        DealStats: IDealStatsResult;
        SearchDeals: ISearchDealsResult;
    }
}

export {};
