// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `ListMessages`. */
export interface IListMessagesResult {
    id: string;
    body: string;
    created_at: Date;
}

/** Result of query `CountMessages`. */
export interface ICountMessagesResult {
    total: string | null;
}

export interface Queries {
    ListMessages: IListMessagesResult;
    CountMessages: ICountMessagesResult;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
