// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `GetUser`. */
export interface IGetUserResult {
    id: IUsersColumns["id"];
    email: IUsersColumns["email"];
    display_name: IUsersColumns["display_name"];
    login_count: IUsersColumns["login_count"];
    is_admin: IUsersColumns["is_admin"];
    created_at: IUsersColumns["created_at"];
}

export interface Queries {
    GetUser: IGetUserResult;
}

/** Columns of `users`. */
export interface IUsersColumns {
    id: string;
    email: string;
    display_name: string | null;
    login_count: number;
    is_admin: boolean;
    created_at: Date;
}

/** Schema of `users`. */
export interface IUsersTable {
    columns: IUsersColumns;
    relationType: (typeof schema)["users"]["_relationType"];
    indexes: keyof (typeof schema)["users"]["_indexes"];
    constraints: keyof (typeof schema)["users"]["_constraints"];
}

export const schema = {
    users: {
        _relationName: "users",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            email: { _columnName: "email", _foreignKeys: {} },
            display_name: { _columnName: "display_name", _foreignKeys: {} },
            login_count: { _columnName: "login_count", _foreignKeys: {} },
            is_admin: { _columnName: "is_admin", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} }
        },
        _indexes: {
            users_pkey: { _indexName: "users_pkey" }
        },
        _constraints: {
            users_pkey: { _constraintName: "users_pkey" }
        }
    }
} as const;

export interface Tables {
    users: IUsersTable;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
