// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `GetArticle`. */
export interface IGetArticleResult {
    id: IArticlesColumns["id"];
    /** Case-insensitive URL slug. */
    slug: IArticlesColumns["slug"];
    title: IArticlesColumns["title"];
    body: IArticlesColumns["body"];
    created_by: IArticlesColumns["created_by"];
}

/** Result of query `ListArticlesWithAuthor`. */
export interface IListArticlesWithAuthorResult {
    id: IArticlesColumns["id"];
    title: IArticlesColumns["title"];
    /** Case-insensitive contact address. */
    email: IAuthorsColumns["email"] | null;
    name: IAuthorsColumns["name"] | null;
}

export interface Queries {
    GetArticle: IGetArticleResult;
    ListArticlesWithAuthor: IListArticlesWithAuthorResult;
}

/** Columns of `articles`. */
export interface IArticlesColumns {
    id: string;
    author_id: string;
    /** Case-insensitive URL slug. */
    slug: string;
    title: string;
    body: string | null;
    created_by: string;
}

/** Schema of `articles`. */
export interface IArticlesTable {
    columns: IArticlesColumns;
    indexes: (typeof schema)["articles"]["indexes"][number];
    constraints: (typeof schema)["articles"]["constraints"][number];
}

/** Columns of `authors`. */
export interface IAuthorsColumns {
    id: string;
    /** Case-insensitive contact address. */
    email: string;
    name: string;
}

/** Schema of `authors`. */
export interface IAuthorsTable {
    columns: IAuthorsColumns;
    indexes: (typeof schema)["authors"]["indexes"][number];
    constraints: (typeof schema)["authors"]["constraints"][number];
}

export const schema = {
    articles: { name: "articles", columns: ["id", "author_id", "slug", "title", "body", "created_by"], indexes: ["articles_author_idx", "articles_pkey", "articles_slug_idx", "articles_slug_key"], constraints: ["articles_author_id_fkey", "articles_pkey", "articles_slug_key"] },
    authors: { name: "authors", columns: ["id", "email", "name"], indexes: ["authors_email_key", "authors_pkey"], constraints: ["authors_email_key", "authors_pkey"] }
} as const;

export interface Tables {
    articles: IArticlesTable;
    authors: IAuthorsTable;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
