// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `GetArticle`. */
export interface IGetArticleResult {
    id: string;
    /** Case-insensitive URL slug. */
    slug: string;
    title: string;
    body: string | null;
    created_by: string;
}

/** Result of query `ListArticlesWithAuthor`. */
export interface IListArticlesWithAuthorResult {
    id: string;
    title: string;
    /** Case-insensitive contact address. */
    email: string | null;
    name: string | null;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults {
        GetArticle: IGetArticleResult;
        ListArticlesWithAuthor: IListArticlesWithAuthorResult;
    }
}

export {};
