import type { EmitModel } from '#types.ts';

// Each query emits one `IFooResult` interface, named so call sites write `sql<IFooResult[]>`.
const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

export const resultName = (name: string): string => `I${cap(name)}Result`;

export function emitQueryTypes(q: EmitModel): string {
  const lines: string[] = [];
  // The file-level `@generated` pragma already marks the whole file; here we only
  // add a doc comment to trace a query back to its explicit `@name`.
  if (q.explicit) {
    lines.push(`/** Result of query \`${q.name}\`. */`);
  }
  if (q.neutralized) {
    lines.push('// NOTE: dynamic clauses (composed fragments) were neutralized for typing;');
    lines.push(
      '// the row shape is unaffected, but verify no dynamic SELECT columns were dropped.',
    );
  }
  lines.push(`export interface ${resultName(q.name)} {`);
  for (const f of q.resultFields) {
    if (f.note) {
      lines.push(`  // ${f.note}`);
    }
    const t = f.nullable ? `${f.ts} | null` : f.ts;
    lines.push(`  ${quoteKey(f.name)}: ${t};`);
  }
  lines.push('}');
  return lines.join('\n');
}

export function emitFile(input: { relSourcePath: string; queries: EmitModel[] }): string {
  // `@generated` on the first line is the recognized pragma — GitHub collapses the
  // file in diffs, Prettier's requirePragma skips it, review tools mark it owned.
  const header =
    `// @generated by bun-sqlgen from ${input.relSourcePath} — do not edit.\n` +
    '// Run the generator to refresh.\n';
  return `${header}\n${input.queries.map(emitQueryTypes).join('\n\n')}\n`;
}

const VALID_IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function quoteKey(k: string): string {
  return VALID_IDENTIFIER.test(k) ? k : JSON.stringify(k);
}
