import ts from 'typescript';
import type { EmitModel, ResolvedField } from '#types.ts';

// Built with the TypeScript factory + printer so output is valid by construction
// (escaping, quoting, formatting handled) rather than assembled from strings. Only
// the data-driven declarations are generated; the fixed `withTypes` runtime below
// is a verbatim snippet — no interpolation, nothing to escape.
const f = ts.factory;
const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
const PRINT_FILE = ts.createSourceFile('queries.gen.ts', '', ts.ScriptTarget.Latest, false);

const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

// Named so call sites can also write the explicit `sql<IFooResult[]>` form.
const resultName = (name: string): string => `I${cap(name)}Result`;

const VALID_IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function propertyName(name: string): ts.PropertyName {
  return VALID_IDENTIFIER.test(name) ? f.createIdentifier(name) : f.createStringLiteral(name);
}

// Parse an arbitrary TS type (`'a' | 'b'`, `string[]`, `{ p: number }`) into a real
// TypeNode, so the printer reproduces it verbatim and validates its syntax.
function typeNode(text: string): ts.TypeNode {
  const sf = ts.createSourceFile('__t.ts', `type __=${text};`, ts.ScriptTarget.Latest, false);
  return (sf.statements[0] as ts.TypeAliasDeclaration).type;
}

function fieldSignature(field: ResolvedField): ts.PropertySignature {
  const type = typeNode(field.nullable ? `${field.ts} | null` : field.ts);
  const sig = f.createPropertySignature(undefined, propertyName(field.name), undefined, type);
  if (field.note) {
    ts.addSyntheticLeadingComment(
      sig,
      ts.SyntaxKind.SingleLineCommentTrivia,
      ` ${field.note}`,
      true,
    );
  }
  return sig;
}

function resultInterface(q: EmitModel): ts.InterfaceDeclaration {
  const node = f.createInterfaceDeclaration(
    [f.createModifier(ts.SyntaxKind.ExportKeyword)],
    resultName(q.name),
    undefined,
    undefined,
    q.resultFields.map(fieldSignature),
  );
  if (q.explicit) {
    ts.addSyntheticLeadingComment(
      node,
      ts.SyntaxKind.MultiLineCommentTrivia,
      `* Result of query \`${q.name}\`. `,
      true,
    );
  }
  if (q.neutralized) {
    for (const line of [
      ' NOTE: dynamic clauses (composed fragments) were neutralized for typing;',
      ' the row shape is unaffected, but verify no dynamic SELECT columns were dropped.',
    ]) {
      ts.addSyntheticLeadingComment(node, ts.SyntaxKind.SingleLineCommentTrivia, line, true);
    }
  }
  return node;
}

// `interface QueryResults { Foo: IFooResult; ... }` — the name→row registry the
// `withTypes` wrapper maps over.
function registryInterface(queries: EmitModel[]): ts.InterfaceDeclaration {
  const node = f.createInterfaceDeclaration(
    [f.createModifier(ts.SyntaxKind.ExportKeyword)],
    'QueryResults',
    undefined,
    undefined,
    queries.map((q) =>
      f.createPropertySignature(
        undefined,
        propertyName(q.name),
        undefined,
        f.createTypeReferenceNode(resultName(q.name)),
      ),
    ),
  );
  ts.addSyntheticLeadingComment(
    node,
    ts.SyntaxKind.MultiLineCommentTrivia,
    '* Maps each query name to its result row type. ',
    true,
  );
  return node;
}

const HEADER =
  '// @generated by bun-sqlgen — do not edit.\n' + '// Run the generator to refresh.\n';

// Fixed boilerplate: Bun's `SQL` augmented with one typed tag per query, and the
// `withTypes` wrapper whose `Proxy` forwards unknown property names to the
// underlying tag at runtime. No interpolation — safe as a verbatim snippet.
const RUNTIME = `type NamedTag<Row> = (strings: TemplateStringsArray, ...values: unknown[]) => Promise<Row[]>;

/** Bun's \`SQL\`, augmented with a typed tag for every generated query name. */
export type TypedSQL = SQL & { readonly [K in keyof QueryResults]: NamedTag<QueryResults[K]> };

/**
 * Wrap a Bun \`SQL\` client so a \`sql.QueryName\` tagged template resolves to the
 * generated row type. Unknown property names forward to the underlying tag, so the
 * untyped \`sql\` escape hatch and real methods (\`sql.begin\`, …) keep working.
 */
export function withTypes(sql: SQL): TypedSQL {
  return new Proxy(sql, {
    get(target, prop, receiver) {
      const existing = Reflect.get(target, prop, receiver);
      if (existing !== undefined) {
        return existing;
      }
      return (strings: TemplateStringsArray, ...values: unknown[]) =>
        (target as (s: TemplateStringsArray, ...v: unknown[]) => unknown)(strings, ...values);
    },
  }) as TypedSQL;
}`;

/**
 * The single aggregated module imported as `withTypes`: every query's result
 * interface, the name→row `QueryResults` registry, and the typed `withTypes`
 * wrapper. Both `sql.Name\`...\`` and `sql<IFooResult[]>\`...\`` read from it.
 */
export function emitModule(input: { queries: EmitModel[] }): string {
  const decls = [...input.queries.map(resultInterface), registryInterface(input.queries)];
  const body = decls
    .map((node) => printer.printNode(ts.EmitHint.Unspecified, node, PRINT_FILE))
    .join('\n\n');
  return `${HEADER}\nimport type { SQL } from 'bun';\n\n${body}\n\n${RUNTIME}\n`;
}
