import type { EmitModel } from '#types.ts';

// Each query emits one `IFooResult` interface, named so call sites write `sql<IFooResult[]>`.
const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

export const resultName = (name: string): string => `I${cap(name)}Result`;

export function emitQueryTypes(q: EmitModel): string {
  const lines: string[] = [];
  // Only name the query when it carries an explicit `@name`; the positional
  // `UnnamedQueryN` fallback isn't worth surfacing.
  lines.push(
    q.explicit ? `/** Generated from query \`${q.name}\` — do not edit. */` : '/** Do not edit. */',
  );
  if (q.neutralized) {
    lines.push('// NOTE: dynamic clauses (composed fragments) were neutralized for typing;');
    lines.push(
      '// the row shape is unaffected, but verify no dynamic SELECT columns were dropped.',
    );
  }
  lines.push(`export interface ${resultName(q.name)} {`);
  for (const f of q.resultFields) {
    if (f.note) {
      lines.push(`  // ${f.note}`);
    }
    const t = f.nullable ? `${f.ts} | null` : f.ts;
    lines.push(`  ${quoteKey(f.name)}: ${t};`);
  }
  lines.push('}');
  return lines.join('\n');
}

export function emitFile(input: { relSourcePath: string; queries: EmitModel[] }): string {
  const header =
    `// AUTO-GENERATED by bun-sqlgen from ${input.relSourcePath}.\n` +
    '// Run the generator to refresh. Do not edit by hand.\n';
  return `${header}\n${input.queries.map(emitQueryTypes).join('\n\n')}\n`;
}

const VALID_IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function quoteKey(k: string): string {
  return VALID_IDENTIFIER.test(k) ? k : JSON.stringify(k);
}
