/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import { command as generateGlobCmd } from './commands/generate/[glob].ts';
import { command as rootCmd } from './commands/_root.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'generate [glob]': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => Promise.resolve(rootCmd) },
  literalChildren: {
    'generate': {
      segment: { kind: 'literal', value: 'generate' },
      command: null,
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'glob' },
        command: { path: 'generate [glob]', load: () => Promise.resolve(generateGlobCmd) },
        literalChildren: {},
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
