import type ts from 'typescript';
import { printNode } from '#emit/ast.ts';
import { augmentation, registryInterface, resultInterface } from '#emit/declarations.ts';
import type { EmitModel } from '#types.ts';

// `@generated` on the first line is what GitHub Linguist looks for to mark the file
// generated (collapsed in diffs, excluded from language stats). Kept as a literal
// header so it's unconditionally first — a declaration's own JSDoc would otherwise
// print ahead of a comment attached to it.
const HEADER = '// @generated by bun-sqlgen — do not edit.\n// Run the generator to refresh.\n';

/**
 * The generated module: each query's (module-local) result interface plus a
 * `declare module` block that augments the package's `QueryResults` registry.
 * Pure types — the `withTypes` runtime ships in the package. `sql.Name\`...\``
 * reads its row type from the registry; name it elsewhere via `QueryResults['Name']`.
 *
 * The trailing `export {}` keeps the file a module so the `declare module` block is
 * a module *augmentation* (it merges into the registry) rather than an ambient
 * module *declaration* (which would replace it) — and keeps the interfaces local
 * instead of leaking into the global scope.
 */
export function emitModule(input: { queries: EmitModel[]; packageName: string }): string {
  const statements: ts.Statement[] = [
    ...input.queries.map(resultInterface),
    registryInterface(input.queries),
    augmentation({ packageName: input.packageName }),
  ];
  return `${HEADER}\n${statements.map(printNode).join('\n\n')}\n\nexport {};\n`;
}
