import ts from 'typescript';
import { printNode } from '#emit/ast.ts';
import { augmentation, resultInterface } from '#emit/declarations.ts';
import type { EmitModel } from '#types.ts';

// `@generated` on the first line is the recognized pragma — review tools mark the
// file owned, diff viewers collapse it. Attached to the first declaration so it's
// part of the printed AST rather than a prepended string.
const BANNER = [' @generated by bun-sqlgen — do not edit.', ' Run the generator to refresh.'];

/**
 * The generated module: each query's result interface plus a `declare module`
 * block that augments the package's `QueryResults` registry. Pure types — the
 * `withTypes` runtime ships in the package. `sql.Name\`...\`` reads its row type
 * from the registry; `sql<IFooResult[]>\`...\`` reads the exported interface.
 */
export function emitModule(input: { queries: EmitModel[]; packageName: string }): string {
  const interfaces = input.queries.map(resultInterface);
  for (const line of BANNER) {
    ts.addSyntheticLeadingComment(
      interfaces[0]!,
      ts.SyntaxKind.SingleLineCommentTrivia,
      line,
      true,
    );
  }
  const statements: ts.Statement[] = [...interfaces, augmentation(input)];
  return `${statements.map(printNode).join('\n\n')}\n`;
}
