// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `GetUserDeals`. */
export interface IGetUserDealsResult {
    id: IUsersColumns["id"];
    email: IUsersColumns["email"];
    display_name: IUsersColumns["display_name"];
    amount: IDealsColumns["amount"] | null;
    updated_at: IUsersColumns["updated_at"];
}

/** Result of query `ListDeals`. */
export interface IListDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
}

/** Result of query `GetDealSummaries`. */
export interface IGetDealSummariesResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    email: IUsersColumns["email"];
    deal_amount: IDealsColumns["amount"];
    total_paid: string | null;
    payment_count: string | null;
    fully_paid: boolean | null;
}

/** Result of query `ListDealDetails`. */
export interface IListDealDetailsResult {
    deal_id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
    email: IUsersColumns["email"];
    display_name: IUsersColumns["display_name"];
    status_upper: string | null;
}

/** Result of query `SearchDeals`. */
export interface ISearchDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
}

/** Result of query `RecentDeals`. */
export interface IRecentDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
}

/** Result of query `GetDealMeta`. */
export interface IGetDealMetaResult {
    id: IDealMetaColumns["id"];
    stage: IDealMetaColumns["stage"];
    tags: IDealMetaColumns["tags"];
    /** Free-form metadata captured during the deal. */
    details: IDealMetaColumns["details"];
    scores: IDealMetaColumns["scores"];
}

/** Result of query `GetDealDetails`. */
export interface IGetDealDetailsResult {
    id: IDealMetaColumns["id"];
    /** Free-form metadata captured during the deal. */
    details: IDealMetaColumns["details"];
}

/** Result of query `CountDeals`. */
export interface ICountDealsResult {
    total: string | null;
}

/** Result of query `NamedUsers`. */
export interface INamedUsersResult {
    id: IUsersColumns["id"];
    display_name: NonNullable<IUsersColumns["display_name"]>;
}

/** Result of query `UserSearchKeys`. */
export interface IUserSearchKeysResult {
    /** Lowercased email, for lookups. */
    search_key: string;
}

/** Result of query `DealSearchKeys`. */
export interface IDealSearchKeysResult {
    /** Lowercased email, for lookups. */
    search_key: string;
}

/** Result of query `OptionalSearchKeys`. */
export interface IOptionalSearchKeysResult {
    /** Lowercased status, for lookups. */
    search_key: string | null;
}

export interface Queries {
    GetUserDeals: IGetUserDealsResult;
    ListDeals: IListDealsResult;
    GetDealSummaries: IGetDealSummariesResult;
    ListDealDetails: IListDealDetailsResult;
    SearchDeals: ISearchDealsResult;
    RecentDeals: IRecentDealsResult;
    GetDealMeta: IGetDealMetaResult;
    GetDealDetails: IGetDealDetailsResult;
    CountDeals: ICountDealsResult;
    NamedUsers: INamedUsersResult;
    UserSearchKeys: IUserSearchKeysResult;
    DealSearchKeys: IDealSearchKeysResult;
    OptionalSearchKeys: IOptionalSearchKeysResult;
}

/** Columns of `deal_details`. */
export interface IDealDetailsColumns {
    deal_id: string | null;
    status: string | null;
    amount: string | null;
    email: string | null;
    display_name: string | null;
    status_upper: string | null;
}

/** Schema of `deal_details`. */
export interface IDealDetailsTable {
    columns: IDealDetailsColumns;
    indexes: (typeof schema)["deal_details"]["indexes"][number];
    constraints: (typeof schema)["deal_details"]["constraints"][number];
}

/** Columns of `deal_meta`. */
export interface IDealMetaColumns {
    id: string;
    deal_id: string;
    stage: "lead" | "negotiation" | "won" | "lost";
    tags: string[];
    /** Free-form metadata captured during the deal. */
    details: {
        priority: number;
        notes: string;
    } | null;
    scores: number[] | null;
}

/** Schema of `deal_meta`. */
export interface IDealMetaTable {
    columns: IDealMetaColumns;
    indexes: (typeof schema)["deal_meta"]["indexes"][number];
    constraints: (typeof schema)["deal_meta"]["constraints"][number];
}

/** Columns of `deals`. */
export interface IDealsColumns {
    id: string;
    user_id: string;
    amount: string;
    status: string;
    /** Lowercased status, for lookups. */
    search_key: string;
}

/** Schema of `deals`. */
export interface IDealsTable {
    columns: IDealsColumns;
    indexes: (typeof schema)["deals"]["indexes"][number];
    constraints: (typeof schema)["deals"]["constraints"][number];
}

/** Columns of `payments`. */
export interface IPaymentsColumns {
    id: string;
    deal_id: string;
    amount: string;
    paid_at: Date;
}

/** Schema of `payments`. */
export interface IPaymentsTable {
    columns: IPaymentsColumns;
    indexes: (typeof schema)["payments"]["indexes"][number];
    constraints: (typeof schema)["payments"]["constraints"][number];
}

/** Columns of `users`. */
export interface IUsersColumns {
    id: string;
    email: string;
    display_name: string | null;
    created_at: Date;
    updated_at: Date;
    /** Lowercased email, for lookups. */
    search_key: string;
}

/** Schema of `users`. */
export interface IUsersTable {
    columns: IUsersColumns;
    indexes: (typeof schema)["users"]["indexes"][number];
    constraints: (typeof schema)["users"]["constraints"][number];
}

export const schema = {
    deal_details: { name: "deal_details", columns: ["deal_id", "status", "amount", "email", "display_name", "status_upper"], indexes: [], constraints: [] },
    deal_meta: { name: "deal_meta", columns: ["id", "deal_id", "stage", "tags", "details", "scores"], indexes: ["deal_meta_pkey"], constraints: ["deal_meta_deal_id_fkey", "deal_meta_pkey"] },
    deals: { name: "deals", columns: ["id", "user_id", "amount", "status", "search_key"], indexes: ["deals_pkey"], constraints: ["deals_pkey", "deals_user_id_fkey"] },
    payments: { name: "payments", columns: ["id", "deal_id", "amount", "paid_at"], indexes: ["payments_pkey"], constraints: ["payments_deal_id_fkey", "payments_pkey"] },
    users: { name: "users", columns: ["id", "email", "display_name", "created_at", "updated_at", "search_key"], indexes: ["users_pkey"], constraints: ["users_pkey"] }
} as const;

export interface Tables {
    deal_details: IDealDetailsTable;
    deal_meta: IDealMetaTable;
    deals: IDealsTable;
    payments: IPaymentsTable;
    users: IUsersTable;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
