/** Result of query `GetUserDeals`. */
// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.
export interface IGetUserDealsResult {
    id: string;
    email: string;
    display_name: string | null;
    amount: string | null;
    updated_at: Date;
}

/** Result of query `ListDeals`. */
export interface IListDealsResult {
    id: string;
    status: string;
    amount: string;
}

/** Result of query `GetDealSummaries`. */
export interface IGetDealSummariesResult {
    id: string;
    status: string;
    email: string;
    deal_amount: string;
    total_paid: string | null;
    payment_count: string | null;
    fully_paid: boolean | null;
}

/** Result of query `ListDealDetails`. */
export interface IListDealDetailsResult {
    deal_id: string;
    status: string;
    amount: string;
    email: string;
    display_name: string | null;
    status_upper: string | null;
}

/** Result of query `SearchDeals`. */
export interface ISearchDealsResult {
    id: string;
    status: string;
    amount: string;
}

/** Result of query `RecentDeals`. */
export interface IRecentDealsResult {
    id: string;
    status: string;
}

/** Result of query `GetDealMeta`. */
export interface IGetDealMetaResult {
    id: string;
    stage: "lead" | "negotiation" | "won" | "lost";
    tags: string[];
    /** Free-form metadata captured during the deal. */
    details: {
        priority: number;
        notes: string;
    } | null;
    scores: number[] | null;
}

/** Result of query `GetDealDetails`. */
export interface IGetDealDetailsResult {
    id: string;
    /** Free-form metadata captured during the deal. */
    details: {
        priority: number;
        notes: string;
    } | null;
}

/** Result of query `countDeals`. */
export interface ICountDealsResult {
    total: string | null;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults {
        GetUserDeals: IGetUserDealsResult;
        ListDeals: IListDealsResult;
        GetDealSummaries: IGetDealSummariesResult;
        ListDealDetails: IListDealDetailsResult;
        SearchDeals: ISearchDealsResult;
        RecentDeals: IRecentDealsResult;
        GetDealMeta: IGetDealMetaResult;
        GetDealDetails: IGetDealDetailsResult;
        countDeals: ICountDealsResult;
    }
}
