// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `GetUserDeals`. */
export interface IGetUserDealsResult {
    id: IUsersColumns["id"];
    email: IUsersColumns["email"];
    display_name: IUsersColumns["display_name"];
    amount: IDealsColumns["amount"] | null;
    updated_at: IUsersColumns["updated_at"];
}

/** Result of query `ListDeals`. */
export interface IListDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
}

/** Result of query `GetDealSummaries`. */
export interface IGetDealSummariesResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    email: IUsersColumns["email"];
    deal_amount: IDealsColumns["amount"];
    total_paid: string | null;
    payment_count: string | null;
    fully_paid: boolean | null;
}

/** Result of query `ListDealDetails`. */
export interface IListDealDetailsResult {
    deal_id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
    email: IUsersColumns["email"];
    display_name: IUsersColumns["display_name"];
    status_upper: string | null;
}

/** Result of query `SearchDeals`. */
export interface ISearchDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
    amount: IDealsColumns["amount"];
}

/** Result of query `RecentDeals`. */
export interface IRecentDealsResult {
    id: IDealsColumns["id"];
    status: IDealsColumns["status"];
}

/** Result of query `GetDealMeta`. */
export interface IGetDealMetaResult {
    id: IDealMetaColumns["id"];
    stage: IDealMetaColumns["stage"];
    tags: IDealMetaColumns["tags"];
    /** Free-form metadata captured during the deal. */
    details: IDealMetaColumns["details"];
    scores: IDealMetaColumns["scores"];
}

/** Result of query `GetDealDetails`. */
export interface IGetDealDetailsResult {
    id: IDealMetaColumns["id"];
    /** Free-form metadata captured during the deal. */
    details: IDealMetaColumns["details"];
}

/** Result of query `CountDeals`. */
export interface ICountDealsResult {
    total: string | null;
}

/** Result of query `NamedUsers`. */
export interface INamedUsersResult {
    id: IUsersColumns["id"];
    display_name: NonNullable<IUsersColumns["display_name"]>;
}

export interface Queries {
    GetUserDeals: IGetUserDealsResult;
    ListDeals: IListDealsResult;
    GetDealSummaries: IGetDealSummariesResult;
    ListDealDetails: IListDealDetailsResult;
    SearchDeals: ISearchDealsResult;
    RecentDeals: IRecentDealsResult;
    GetDealMeta: IGetDealMetaResult;
    GetDealDetails: IGetDealDetailsResult;
    CountDeals: ICountDealsResult;
    NamedUsers: INamedUsersResult;
}

/** Columns of `deal_details`. */
export interface IDealDetailsColumns {
    deal_id: string | null;
    status: string | null;
    amount: string | null;
    email: string | null;
    display_name: string | null;
    status_upper: string | null;
}

/** Schema of `deal_details`. */
export interface IDealDetailsTable {
    columns: IDealDetailsColumns;
    indexes: never;
    constraints: never;
}

/** Columns of `deal_meta`. */
export interface IDealMetaColumns {
    id: string;
    deal_id: string;
    stage: "lead" | "negotiation" | "won" | "lost";
    tags: string[];
    /** Free-form metadata captured during the deal. */
    details: {
        priority: number;
        notes: string;
    } | null;
    scores: number[] | null;
}

/** Schema of `deal_meta`. */
export interface IDealMetaTable {
    columns: IDealMetaColumns;
    indexes: "deal_meta_pkey";
    constraints: "deal_meta_deal_id_fkey" | "deal_meta_pkey";
}

/** Columns of `deals`. */
export interface IDealsColumns {
    id: string;
    user_id: string;
    amount: string;
    status: string;
}

/** Schema of `deals`. */
export interface IDealsTable {
    columns: IDealsColumns;
    indexes: "deals_pkey";
    constraints: "deals_pkey" | "deals_user_id_fkey";
}

/** Columns of `payments`. */
export interface IPaymentsColumns {
    id: string;
    deal_id: string;
    amount: string;
    paid_at: Date;
}

/** Schema of `payments`. */
export interface IPaymentsTable {
    columns: IPaymentsColumns;
    indexes: "payments_pkey";
    constraints: "payments_deal_id_fkey" | "payments_pkey";
}

/** Columns of `users`. */
export interface IUsersColumns {
    id: string;
    email: string;
    display_name: string | null;
    created_at: Date;
    updated_at: Date;
}

/** Schema of `users`. */
export interface IUsersTable {
    columns: IUsersColumns;
    indexes: "users_pkey";
    constraints: "users_pkey";
}

export interface Tables {
    deal_details: IDealDetailsTable;
    deal_meta: IDealMetaTable;
    deals: IDealsTable;
    payments: IPaymentsTable;
    users: IUsersTable;
}

declare module "@repo/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
