// @generated by bun-sqlgen from src/queries.ts — do not edit.
// Run the generator to refresh.

/** Result of query `getUserDeals`. */
export interface IGetUserDealsResult {
  id: string;
  email: string;
  display_name: string | null;
  amount: string | null;
  updated_at: Date;
}

/** Result of query `listDeals`. */
export interface IListDealsResult {
  id: string;
  status: string;
  amount: string;
}

/** Result of query `getDealSummaries`. */
export interface IGetDealSummariesResult {
  id: string;
  status: string;
  email: string;
  deal_amount: string;
  total_paid: string | null;
  payment_count: string | null;
  fully_paid: boolean | null;
}

/** Result of query `listDealDetails`. */
export interface IListDealDetailsResult {
  deal_id: string;
  status: string;
  amount: string;
  email: string;
  display_name: string | null;
  status_upper: string | null;
}

/** Result of query `searchDeals`. */
export interface ISearchDealsResult {
  id: string;
  status: string;
  amount: string;
}

/** Result of query `recentDeals`. */
export interface IRecentDealsResult {
  id: string;
  status: string;
}

/** Result of query `getDealMeta`. */
export interface IGetDealMetaResult {
  id: string;
  stage: 'lead' | 'negotiation' | 'won' | 'lost';
  tags: string[];
  details: unknown | null;
  scores: number[] | null;
}

/** Result of query `getDealDetails`. */
export interface IGetDealDetailsResult {
  id: string;
  details: { priority: number; notes: string } | null;
}

export interface IUnnamedQuery1Result {
  total: string | null;
}
