// AUTO-GENERATED by bun-sqlgen from src/queries.ts.
// Run the generator to refresh. Do not edit by hand.

/** Generated from query `getUserDeals` — do not edit. */
export interface IGetUserDealsResult {
  id: string;
  email: string;
  display_name: string | null;
  amount: string | null;
  updated_at: Date;
}

/** Generated from query `listDeals` — do not edit. */
export interface IListDealsResult {
  id: string;
  status: string;
  amount: string;
}

/** Generated from query `getDealSummaries` — do not edit. */
export interface IGetDealSummariesResult {
  id: string;
  status: string;
  email: string;
  deal_amount: string;
  total_paid: string | null;
  payment_count: string | null;
  fully_paid: boolean | null;
}

/** Generated from query `listDealDetails` — do not edit. */
export interface IListDealDetailsResult {
  deal_id: string;
  status: string;
  amount: string;
  email: string;
  display_name: string | null;
  status_upper: string | null;
}

/** Generated from query `searchDeals` — do not edit. */
export interface ISearchDealsResult {
  id: string;
  status: string;
  amount: string;
}

/** Generated from query `recentDeals` — do not edit. */
export interface IRecentDealsResult {
  id: string;
  status: string;
}

/** Generated from query `getDealMeta` — do not edit. */
export interface IGetDealMetaResult {
  id: string;
  stage: 'lead' | 'negotiation' | 'won' | 'lost';
  tags: string[];
  details: unknown | null;
  scores: number[] | null;
}

/** Generated from query `getDealDetails` — do not edit. */
export interface IGetDealDetailsResult {
  id: string;
  details: { priority: number; notes: string } | null;
}

/** Do not edit. */
export interface IUnnamedQuery1Result {
  total: string | null;
}
